OPP Student Library - Basic UI
muskan2532150/OOP-school-library pull request #4
Opened 2022-11-11 18:53 UTC by muskan2532150

-  Create an app.rb file to serve as your console app entry point. It should have methods that do the following:

      - List all books.
      - List all people.
      - Create a person (teacher or student, not a plain Person).
      -  Create a book.
      -  Create a rental.
      -  List all rentals for a given person's id.

- In your main.rb define the entry point, this will be a method called main invoked at the end of your file. This method should 
    do the following:
    -  Present the user with a list of options to perform.
    -  Lets users choose an option.
    -  If needed, ask for parameters for the option.
    -  Have a way to quit the app.

2022-11-11 19:38 UTC, mmsesay requested changes
Hi @muskan2532150, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
 - Good Readme :heavy_check_mark: 
 - No linter error :heavy_check_mark: 
 - Good PR title :heavy_check_mark: 
 - Good PR summary :heavy_check_mark:  


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-11 19:38 UTC, mmsesay commented on README.md
> +npm install
- [ ] `npm install` doesn't work for ruby. Please refactor to `bundle install`

2022-11-11 19:38 UTC, mmsesay commented on README.md
> +```
- [OPTIONAL] I don't think this is step is vital for a ruby project

2022-11-11 19:38 UTC, mmsesay commented on app.rb
> +          puts "Date: #{rental.date} Book: #{rental.book.title} by #{rental.book.author}"
- [ ] Only the year of the rental date is been displayed. Please work on it to show the entire date entered by the user.

Your App Output |
:-------------------:|
<img width="253" alt="Screen Shot 2022-11-11 at 7 34 58 PM" src="https://user-images.githubusercontent.com/39523312/201417059-a2c12c8d-c6ee-46dd-821c-37dcfb65e32a.png"> |

Expected Output |
:-------------------:|
![Screen Shot 2022-11-11 at 7 37 22 PM](https://user-images.githubusercontent.com/39523312/201417138-ba25da4a-b93a-4298-9496-f610facb2635.png) |

2022-11-12 07:34 UTC, VICTOR-CHUKWU approved these changes
Hi @muskan2532150 , 
# STATUS: APPROVED! 🥇 💯 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- [ ] All linters passed

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-12 07:48 UTC, merged